version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: fitByte-postgres
    environment:
      POSTGRES_DB: fitByte
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - fitByte_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: go-minio
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9090" /data

volumes:
  fitByte_data: