app:
  port: 8081

database:
  host: 127.0.0.1
  port: 5433
  username: user
  password: password
  dbname: fitByte

secret:
  jwt_secret: "secret"

minio:
  endpoint: "localhost:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  use_ssl: false
  bucket: "fitbyte"